name: geo_triangle_grid
description: A package for creating a triangle grid on a map. The grid is created by dividing the map into icosphere with 20 triangles and each triangle is divided into 4 smaller triangles and so on.
version: 1.0.1
repository: https://github.com/triangle-int/dart_geo_triangle_grid

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
