name: geo_triangle_grid
description: A package for creating a triangle grid on a map and converting them into hash for fast search.
version: 1.1.0
repository: https://github.com/triangle-int/dart_geo_triangle_grid

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
